[package]
name = "jus-rs"
version = "0.0.1"
edition = "2021"

[dependencies]
nom = "7.1.3"
serde_json = "1.0.128"
thiserror = "1.0.64"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "compile"
harness = false

[[bench]]
name = "validate"
harness = false


